export type CalendarRace = {
  month: "Septiembre" | "Octubre" | "Noviembre" | "Diciembre";
  day: number;
  weekday: string;
  name: string;
  city: string;
  distances: string;
  note?: string;
};

const race = (month: CalendarRace["month"], day: number, weekday: string, name: string, city: string, distances: string, note?: string): CalendarRace => ({ month, day, weekday, name, city, distances, note });

// Datos proporcionados por Nómada Race a partir del calendario 2026 de Corre.cl.
export const calendarRaces: CalendarRace[] = [
  race("Septiembre", 11, "Viernes", "Pachamanka Ultra Trail", "Doñihue", "10, 25, 50 y 80 km"),
  race("Septiembre", 12, "Sábado", "Media Maratón Pucón–Caburgua", "Pucón", "5, 10 y 21 km"),
  race("Septiembre", 12, "Sábado", "Corrida Nocturna", "Tocopilla", "1.5 y 5 km"),
  race("Septiembre", 12, "Sábado", "Running Agua de Chincol", "Petorca", "1, 5, 10 y 21 km"),
  race("Septiembre", 12, "Sábado", "Campeonato de Cross Country AB Atletismo", "Santiago, El Bosque", "300 m a 4 km"),
  race("Septiembre", 12, "Sábado", "Corrida de Fiestas Patrias Campanario", "Yungay", "1.5 y 5 km", "Nueva fecha"),
  race("Septiembre", 12, "Sábado", "Torneo de Pruebas Medio Fondo y Salto", "Santiago, Maipú", "200 m a 1.5 km"),
  race("Septiembre", 13, "Domingo", "Desafío Trail Running – Santa Martina", "Santiago, Lo Barnechea", "5, 12 y 25 km"),
  race("Septiembre", 13, "Domingo", "Corrida Familiar Maipú", "Santiago, Maipú", "5 y 10 km"),
  race("Septiembre", 13, "Domingo", "Control 30K", "Melipilla", "5, 10, 21 y 30 km"),
  race("Septiembre", 13, "Domingo", "Corrida Glorias del Ejército", "Santiago, Las Condes", "3, 5 y 10 km"),
  race("Septiembre", 13, "Domingo", "Desafío Entre Volcanes – Km Vertical", "Puerto Varas", "6 km"),
  race("Septiembre", 13, "Domingo", "Carrera 21K Puerto Montt", "Puerto Montt", "2, 5, 10 y 21 km"),
  race("Septiembre", 19, "Sábado", "Cross Country Fiestas Patrias", "Santiago, Independencia", "500 m; 1, 2 y 3 km"),
  race("Septiembre", 26, "Sábado", "Alhué Trail Run", "Alhué", "3, 12, 21 y 30 km"),
  race("Septiembre", 26, "Sábado", "Ultra Paine", "Torres del Paine", "5 a 50 km"),
  race("Septiembre", 26, "Sábado", "Media Maratón Cuesta Lastarria Loncoche", "Loncoche", "400 m; 5, 10 y 21 km"),
  race("Septiembre", 27, "Domingo", "Ideal Global Race", "Santiago, Las Condes", "1, 3, 5 y 10 km"),
  race("Septiembre", 27, "Domingo", "Reforest Running On Tour Rancagua/Machalí", "Rancagua", "3, 5 y 10 km"),
  race("Septiembre", 27, "Domingo", "Corrida Familiar Tuniche", "Graneros", "3, 5, 10 y 21 km"),
  race("Septiembre", 27, "Domingo", "Corrida Familiar UCM", "Curicó", "3 km"),
  race("Septiembre", 27, "Domingo", "Media Maratón Longotoma", "La Ligua", "3, 5, 10 y 21 km"),
  race("Septiembre", 27, "Domingo", "Corre Puerto Nuevo La Unión", "La Unión", "3, 5, 10 y 21 km"),
  race("Septiembre", 27, "Domingo", "Desafío Alto Concepción", "Concepción", "10 y 21 km"),
  race("Septiembre", 27, "Domingo", "Corrida Fiestas Patrias Pillanlelbún", "Lautaro", "50 m a 5 km"),

  race("Octubre", 3, "Sábado", "Cascada Trail by Jetour", "San José de Maipo", "3 a 30 km"),
  race("Octubre", 3, "Sábado", "Paillaco Corre", "Paillaco", "3, 6, 10 y 15 km"),
  race("Octubre", 3, "Sábado", "Campeonato de Cross Country AB Atletismo", "Santiago, El Bosque", "300 m a 4 km"),
  race("Octubre", 3, "Sábado", "Eres Importante Para Mí", "Temuco", "8 km"),
  race("Octubre", 4, "Domingo", "Maratón de Viña del Mar", "Viña del Mar", "10, 21 y 42 km", "Nuevo"),
  race("Octubre", 4, "Domingo", "Corriendo entre Montañas", "Antuco", "3, 6, 10 y 21 km"),
  race("Octubre", 4, "Domingo", "Iron Can", "Santiago, La Reina", "2.5 km", "Mascotas"),
  race("Octubre", 4, "Domingo", "Corrida Aniversario Independencia", "Santiago, Independencia", "5 y 10 km"),
  race("Octubre", 4, "Domingo", "Media Maratón Fernando Delgado", "San Pablo", "1.6 a 21 km"),
  race("Octubre", 4, "Domingo", "Trail Running Requínoa", "Requínoa", "5 y 10 km"),
  race("Octubre", 4, "Domingo", "Rükapillan 21K – Medio Maratón de Villarrica", "Villarrica", "2.5, 5, 10 y 21 km"),
  race("Octubre", 10, "Sábado", "Trilogía Trail Running Biobío", "San Pedro de la Paz", "Por confirmar"),
  race("Octubre", 10, "Sábado", "Desafío Altopower", "San Rafael", "6 km", "Obstáculos"),
  race("Octubre", 11, "Domingo", "Por La Ruta del Duende", "Puerto Octay", "2, 8 y 15 km"),
  race("Octubre", 11, "Domingo", "Trail by Canteras", "Angol", "2, 8, 15 y 21 km"),
  race("Octubre", 11, "Domingo", "Corramos Juntas – Cáncer de Mamas", "Santiago, La Reina", "5 y 7 km", "Por confirmar"),
  race("Octubre", 11, "Domingo", "Desafío San Ambrosio Trail", "Los Lagos", "2 a 25 km"),
  race("Octubre", 11, "Domingo", "Caleu Backyard", "Til Til", "10.5 km"),
  race("Octubre", 11, "Domingo", "Corrida Aniversario PDI", "Santiago, Estación Central", "5 y 10 km"),
  race("Octubre", 11, "Domingo", "Trail Running Parque Cantillana", "Paine", "3, 7, 12 y 17 km"),
  race("Octubre", 11, "Domingo", "Trail La Fragua", "Curacaví", "5, 10 y 20 km"),
  race("Octubre", 11, "Domingo", "Colchagua Run", "Santa Cruz", "2, 5 y 10 km"),
  race("Octubre", 11, "Domingo", "Corrida Solidaria Duoc UC Puente Alto", "Santiago, Puente Alto", "2, 3.5 y 7 km"),
  race("Octubre", 11, "Domingo", "Corrida Desafío Papal", "Empedrado", "3, 7 y 15 km", "Nuevo"),
  race("Octubre", 17, "Sábado", "The North Face Endurance Trail", "Santiago", "10 a 160 km"),
  race("Octubre", 17, "Sábado", "Garganta del Diablo Trail Running", "Pica", "5, 10 y 21 km"),
  race("Octubre", 17, "Sábado", "Santander Rock ‘n’ Roll Running Series", "Santiago, Lo Barnechea", "5, 10 y 21 km"),
  race("Octubre", 17, "Sábado", "Huellelhue Trail Challenge", "Valdivia", "8, 15, 21 y 32 km"),
  race("Octubre", 17, "Sábado", "Festival Vista Baker", "Cochrane", "7, 14, 21 y 32 km"),
  race("Octubre", 17, "Sábado", "Trail Jorge Roa Manríquez", "Nacimiento", "2.5, 7 y 12 km"),
  race("Octubre", 17, "Sábado", "Travesía Tutuca", "Romeral", "5, 12 y 21 km"),
  race("Octubre", 17, "Sábado", "Campeonato de Cross Country AB Atletismo", "Santiago, El Bosque", "300 m a 4 km"),
  race("Octubre", 17, "Sábado", "Cross Country Angol", "Angol", "500 m a 6 km"),
  race("Octubre", 18, "Domingo", "Trail Eco Run Papudo", "Papudo", "3.5, 7, 15 y 25 km"),
  race("Octubre", 18, "Domingo", "Dog Race", "Santiago, Providencia", "2 y 3 km", "Por confirmar"),
  race("Octubre", 18, "Domingo", "STGO10K by ASICS", "Santiago", "5 y 10 km"),
  race("Octubre", 18, "Domingo", "Corrida Familiar San Judas Tadeo", "Malloa", "3, 6 y 10 km"),
  race("Octubre", 18, "Domingo", "Corrida por el Cáncer", "Los Ángeles", "3 y 6 km"),
  race("Octubre", 18, "Domingo", "Carnaval Deportivo Color", "Concepción", "3 y 5 km"),
  race("Octubre", 18, "Domingo", "Muévete x Nosotras", "Temuco", "3, 5 y 10 km"),
  race("Octubre", 18, "Domingo", "Media Maratón Donde Corre el Viento", "Curepto", "10 y 21 km"),
  race("Octubre", 18, "Domingo", "Desafío Columpio de los Deseos", "San Rosendo", "3, 7, 11 y 21 km"),
  race("Octubre", 24, "Sábado", "Climbing Tour", "Mostazal", "5, 7 y 15 km"),
  race("Octubre", 24, "Sábado", "Rinconada Corre", "Rinconada", "5, 10 y 21 km"),
  race("Octubre", 24, "Sábado", "Sanjo 10/21K", "Aysén", "10 y 21 km"),
  race("Octubre", 24, "Sábado", "Titan Race", "Isla de Maipo", "5 y 8 km", "Obstáculos"),
  race("Octubre", 24, "Sábado", "Desafío La Sepultura", "San Vicente", "5, 10 y 20 km"),
  race("Octubre", 24, "Sábado", "Cosacos Trail", "Talcahuano", "7.5, 16 y 24 km"),
  race("Octubre", 25, "Domingo", "Ovalle Half Marathon", "Ovalle", "5, 10 y 21 km", "Actualizado"),
  race("Octubre", 25, "Domingo", "Cross del Terror", "Valparaíso", "2, 5 y 10 km"),
  race("Octubre", 25, "Domingo", "Talagante Corre", "Talagante", "3 y 12 km"),
  race("Octubre", 25, "Domingo", "Corrida por la Vida Yo Mujer", "Santiago, Vitacura", "3, 5 y 10 km"),
  race("Octubre", 25, "Domingo", "CMPC Frontera Trail", "Temuco", "3, 7, 15 y 40 km"),
  race("Octubre", 25, "Domingo", "Corrida Chicureo", "Colina", "3, 6 y 12 km"),
  race("Octubre", 25, "Domingo", "Reforest Running Penco/Gran Concepción", "Penco", "3, 5 y 10 km"),
  race("Octubre", 25, "Domingo", "Medio Maratón Lago Ranco", "Lago Ranco", "3, 5, 10 y 21 km"),
  race("Octubre", 25, "Domingo", "Kankura Trail Run", "Palmilla", "7, 14 y 21 km"),
  race("Octubre", 25, "Domingo", "Media Maratón del Bío Bío", "Concepción", "2, 5, 10 y 21 km"),
  race("Octubre", 25, "Domingo", "Maule Corre", "Linares", "800 m; 3, 5 y 10 km"),
  race("Octubre", 27, "Martes", "Sprint Run Suyai", "Vilcún", "50 m a 1.2 km"),
  race("Octubre", 31, "Sábado", "Trail Nocturno Santiago Aguas Andinas", "Santiago, La Reina", "4, 7, 12 y 19 km", "Nuevo"),
  race("Octubre", 31, "Sábado", "Manzanar Trail Running – Curacautín Trail Series", "Curacautín", "2.5, 6, 11 y 22 km"),
  race("Octubre", 31, "Sábado", "Tulahuén Fest", "Monte Patria", "10, 21 y 42 km"),
  race("Octubre", 31, "Sábado", "Trilogía Valle Las Trancas", "Pinto", "2, 10, 16 y 25 km"),
  race("Octubre", 31, "Sábado", "The Last Run", "Santiago, Providencia", "6 y 9 km"),

  race("Noviembre", 1, "Domingo", "Corrida/Caminata por el Cáncer Temuco", "Temuco", "3.5, 5 y 10 km"),
  race("Noviembre", 7, "Sábado", "Trail Altas Cumbres", "Santiago, Puente Alto", "4, 7, 14 y 21 km"),
  race("Noviembre", 7, "Sábado", "Trail Ruta del Puma", "Concepción", "3, 10, 14 y 21 km"),
  race("Noviembre", 7, "Sábado", "Machalí Trail Race", "Machalí", "1, 6 y 18 km"),
  race("Noviembre", 7, "Sábado", "Corrida Familiar EPV Quilitapia", "Combarbalá", "2, 4, 8 y 20 km"),
  race("Noviembre", 7, "Sábado", "Corrida por La Inclusión", "Santiago, La Granja", "500 m; 1, 3 y 5 km"),
  race("Noviembre", 8, "Domingo", "Ruta Ancestral Diaguitas Trail", "Ovalle", "3, 10 y 25 km"),
  race("Noviembre", 8, "Domingo", "Corriendo al Centenario PUCV", "Valparaíso", "3 y 10 km"),
  race("Noviembre", 8, "Domingo", "Corrida Soy Más Fit La Pintana", "Santiago, La Pintana", "3 y 10 km"),
  race("Noviembre", 8, "Domingo", "Corrida Chillán", "Chillán", "5.5 y 11 km"),
  race("Noviembre", 8, "Domingo", "Corrida Conecta", "Temuco", "5 y 10 km"),
  race("Noviembre", 8, "Domingo", "Objetivo Tenglo", "Puerto Montt", "5, 8 y 15 km"),
  race("Noviembre", 8, "Domingo", "The Color Run Santiago", "Santiago, Huechuraba", "5 km"),
  race("Noviembre", 8, "Domingo", "Desafío Challupén Trail", "Villarrica", "5, 10 y 21 km"),
  race("Noviembre", 8, "Domingo", "Corrida 184 Años de la Universidad de Chile", "Santiago Centro", "5 y 10 km"),
  race("Noviembre", 14, "Sábado", "GTVUT Las Trancas", "Pinto", "18, 30 y 50 km"),
  race("Noviembre", 14, "Sábado", "Night Run Curauma", "Valparaíso", "5 y 11.5 km"),
  race("Noviembre", 15, "Domingo", "Media Maratón de Nogales", "Nogales", "5, 10 y 21 km"),
  race("Noviembre", 15, "Domingo", "Maratón Topman Pucón", "Pucón", "10, 21 y 42 km"),
  race("Noviembre", 15, "Domingo", "FEDACHI Marathon", "Santiago, Ñuñoa", "5, 10, 21 y 42 km"),
  race("Noviembre", 15, "Domingo", "Corrida Familiar Lagunas de Concepción", "Concepción", "3, 5 y 10 km"),
  race("Noviembre", 15, "Domingo", "Media Maratón Kallfuko Run Fest", "Calbuco", "2, 5, 10 y 21 km"),
  race("Noviembre", 15, "Domingo", "Cross Country RD", "Ovalle", "2.5 y 10 km"),
  race("Noviembre", 15, "Domingo", "Corrida MagiK por los Niños con Cáncer", "Santiago, Providencia", "2 y 5 km"),
  race("Noviembre", 15, "Domingo", "Corrida Solidaria Duoc UC San Bernardo", "Santiago, San Bernardo", "2, 3.5 y 7 km"),
  race("Noviembre", 21, "Sábado", "Columbia Trail Challenge Huilo Huilo", "Panguipulli", "2 a 60 km", "Nuevo"),
  race("Noviembre", 22, "Domingo", "Corrida TECHO-Chile", "Santiago Centro", "2, 5 y 10 km"),
  race("Noviembre", 22, "Domingo", "Corrida de Llacolén", "San Pedro de la Paz", "5 y 10 km"),
  race("Noviembre", 22, "Domingo", "Reforest Running Viña del Mar", "Valparaíso", "3, 5 y 10 km"),
  race("Noviembre", 22, "Domingo", "Corrida Familiar Lasallista", "Temuco", "2, 4 y 6 km"),
  race("Noviembre", 22, "Domingo", "Corrida Familiar UCM Talca", "Talca", "Por confirmar"),
  race("Noviembre", 22, "Domingo", "Gran Carrera UBB", "Concepción", "3 y 6 km", "Por confirmar"),
  race("Noviembre", 22, "Domingo", "Corrida Villa Alemana 10K", "Villa Alemana", "3 y 10 km"),
  race("Noviembre", 27, "Viernes", "Family Run Valdivia", "Valdivia", "3 y 5 km"),
  race("Noviembre", 28, "Sábado", "La Gran Travesía", "San José de Maipo", "55 y 100 km"),
  race("Noviembre", 28, "Sábado", "Ñuñoa 10K Nocturna", "Santiago, Ñuñoa", "3, 5 y 10 km"),
  race("Noviembre", 28, "Sábado", "Roman Race OCR Trailrun", "Curicó", "2, 5 y 12 km", "Inscripciones"),
  race("Noviembre", 29, "Domingo", "Gran Corrida Diario El Sur", "Concepción", "2, 5 y 10 km", "Nuevo"),
  race("Noviembre", 29, "Domingo", "21K Valparaíso – Desafío Faro Punta de Ángeles", "Valparaíso", "5 y 21 km"),
  race("Noviembre", 29, "Domingo", "K Kids Race", "Puerto Varas", "250 m a 4 km", "Niños"),
  race("Noviembre", 29, "Domingo", "Corrida Santiago CCS", "Santiago Centro", "5 y 15 km", "Por confirmar"),

  race("Diciembre", 5, "Sábado", "Desafío Captrén Laguna Negra", "Curacautín", "2, 6, 14 y 24 km"),
  race("Diciembre", 6, "Domingo", "Concón 10K", "Concón", "3 y 10 km"),
  race("Diciembre", 6, "Domingo", "Media Maratón del Trueno", "Talca", "5, 10 y 21 km"),
  race("Diciembre", 6, "Domingo", "Corrida Gana Santiago", "Santiago Centro", "5, 10 y 21 km"),
  race("Diciembre", 6, "Domingo", "Condorito Run", "Río Claro", "2, 7 y 12 km", "Nueva fecha"),
  race("Diciembre", 6, "Domingo", "Corrida Atlética Aniversario de Gendarmería", "Melipilla", "4.5 km"),
  race("Diciembre", 6, "Domingo", "Vulcano Ultra Trail", "Puerto Varas", "9 a 103 km", "Actualizado"),
  race("Diciembre", 6, "Domingo", "Corrida Solidaria Duoc UC Plaza Norte", "Santiago, Huechuraba", "2, 4 y 8 km", "Nuevo"),
  race("Diciembre", 7, "Lunes", "Sky Race Ojos del Salado", "Copiapó", "Por confirmar"),
  race("Diciembre", 13, "Domingo", "Maratón del Mataquito", "Rauco", "11, 21 y 42 km"),
  race("Diciembre", 13, "Domingo", "Smart Fit Run", "Santiago, Ñuñoa", "3, 5 y 10 km"),
  race("Diciembre", 13, "Domingo", "Newen Trail Kallfuko", "Puerto Montt", "2 a 30 km"),
  race("Diciembre", 13, "Domingo", "Maratón del Biobío", "Concepción", "2, 5, 10 y 21 km", "Nuevo"),
  race("Diciembre", 19, "Sábado", "Antuco Trail – Ruta del Cóndor", "Antuco", "2 a 46 km"),
  race("Diciembre", 19, "Sábado", "Lagunas Andinas Trail", "Panguipulli", "2 a 20 km"),
  race("Diciembre", 20, "Domingo", "Desafío Trail Running ParqueMet – Caja Los Andes", "Santiago, Providencia", "5, 10 y 23 km"),
  race("Diciembre", 20, "Domingo", "Final del Circuito Team Family Erices", "Valparaíso", "2, 5 y 10 km"),
  race("Diciembre", 20, "Domingo", "Zeo Sport Challenger", "Chiguayante", "3 y 10 km"),
  race("Diciembre", 26, "Sábado", "Thund3r Hybrid Ironside", "Santiago, Ñuñoa", "4 y 6.4 km"),
  race("Diciembre", 27, "Domingo", "Trail Espíritu Runners Bienestar Pitama", "Casablanca", "3, 7, 12 y 21 km"),
  race("Diciembre", 27, "Domingo", "San Silvestre Curicana", "Curicó", "6 y 12 km"),
  race("Diciembre", 31, "Jueves", "Corrida Atlética Familiar San Silvestre Pomaire", "Melipilla", "8.5 km"),
];
